### ISSUE TITLE
0.5.2 break existing code that use FontFile::new_from_data

### ISSUE THREAD

**Issue by Rhuagh** [vvuk/dwrote-rs#13]
font-kit broke on Windows because of this. API changes should only be done in minor version updates, not patch versions for this reason. Could you yank yesterdays update and reversion it to 0.6 ?

**Comment by Rhuagh** [comment]
https://media.discordapp.net/attachments/476032191567233025/502758946126430208/unknown.png

**Comment by jrmuizel** [comment]
This repo is dead. You should report here: https://github.com/servo/dwrote-rs

**Comment by Rhuagh** [comment]
Ah, thanks.
