### ISSUE TITLE
Add support for raw fonts

### ISSUE THREAD

**Issue by vvuk** [vvuk/dwrote-rs#3]
Need to add support for IDWriteFontFileLoader/FontStream etc. to create a FontFile from bytes.

**Comment by jrmuizel** [comment]
Will this still build with stable rust while using #![feature(concat_idents)]?

**Comment by vvuk** [comment]
Probably not. I wasn't sure we were using stable on Gecko. I can probably
work around it.

**Comment by jrmuizel** [comment]
We are currently using stable rust in Gecko

**Comment by vvuk** [comment]
Well that's annoying
